[mySQLConfig]
uri = "root:root@tcp(localhost:3306)/eventCacker"
database = "mysql"
addr = "localhost:3306"
user = "root"
password = "root"
dbName ="eventCacker"
maxIdleConns = 5
maxOpenConns = 30
connMaxLifetime = 180

[elastic]
uri = "http://localhost:9200"
user = "123"
password = "123"